### ISSUE TITLE
Noticed is slower when importing a library

### ISSUE THREAD

**Issue by nrgapple** [sebbekarlsson/fjb#21]
https://github.com/sebbekarlsson/fjb/blame/master/benchmarks.md#L436

Could you explain why this would not be a draw back?

Wouldn't importing be something most people would be doing?

**Comment by sebbekarlsson** [comment]
@nrgapple 

A bit slower in this case.
However, my tree shaking algorithm seems a bit better here.

My output is significantly smaller in the benchmark with importing ceil from lodash.

I'm pretty sure FJB will be faster soon as well.

Haven't really optimized it yet.

**Comment by sebbekarlsson** [comment]
It's a bit faster now then previously, after my performance optimizations.
https://github.com/sebbekarlsson/fjb/commit/633b4312592bb53b81b67b31113e3d8415d313fc#diff-2d71c342ff98e42cb816fc8f114211780edeb28e8bbcd30d52026972d2e4800fR422

However, still not fast enough.

I'm working on it

**Comment by sebbekarlsson** [comment]
Made significant improvements now.

However, I can only be faster than `esbuild` to a certain extent.
The reason is, my tree shaking algorithm is significantly more sophisticated in certain areas.

For example, when importing `{ ceil }` from lodash.
At the time writing this, my output size is ` 2195 bytes` and esbuild output size is `73253 bytes`.

And this comes with a price; being slightly slower.


I'm closing this issue for now.
